Repository FHellmann/Uniatron, pull requests merged in 2018-07, with the labels that each got.

#59 Redesign navigation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/MainActivity.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/MainActivityViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/NonSwipeableViewPager.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/history/HistoryFragment.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/history/HistoryViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/home/HomeFragment.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/home/HomeViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/home/shop/TimeCreditShopViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingActivity.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingFragment.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingViewModel.java
  app/src/main/res/drawable/ic_directions_walk_white_24dp.xml
  app/src/main/res/drawable/ic_history_white_24dp.xml
  app/src/main/res/drawable/ic_home_white_24dp.xml
  app/src/main/res/drawable/ic_local_play_black_24dp.xml
  app/src/main/res/drawable/ic_phonelink_lock_white_24dp.xml
  app/src/main/res/drawable/ic_shopping_cart_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_history_loading.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/history.xml
  app/src/main/res/menu/home.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  domain/src/androidTest/java/com/edu/uni/augsburg/uniatron/domain/DataRepositoryTest.java
  domain/src/androidTest/java/com/edu/uni/augsburg/uniatron/domain/DatabaseUtil.java
  domain/src/androidTest/java/com/edu/uni/augsburg/uniatron/domain/dao/SummaryDaoTest.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/DataRepository.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/dao/SummaryDao.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/util/DateUtil.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/model/LearningAid.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/util/DateUtilTest.java
Labels: enhancement

#60 Dh 7 applock
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/edu/uni/augsburg/uniatron/MainApplication.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/SharedPreferencesHandler.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/notification/NotificationChannels.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/notification/builder/TimeUpNotificationBuilder.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/service/AppTrackingService.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/service/BroadcastService.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/service/StepCountService.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/service/handler/BootCompletedHandler.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/MainActivity.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingViewModel.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/edu/uni/augsburg/uniatron/model/TimeCredits.java
Labels: enhancement

#69 Documentation
  README.md
  Uniatron-Presentation0706.pptx
  Uniatron-Presentation1207.pptx
Labels: Documentation

#71 Update final presentation, README and add unit tests
  README.md
  Uniatron-Presentation1207.pptx
  doc/Play Store/0_Play-Store_Functiongraph-Part.png
  doc/Play Store/0_Play-Store_Functiongraph.png
  doc/Play Store/1_Play-Store.png
  doc/Play Store/2_Play-Store.png
  doc/Play Store/3_Play-Store.png
  doc/Play Store/Screenshot_About.png
  doc/Play Store/Screenshot_History.png
  doc/Play Store/Screenshot_Home.png
  doc/Play Store/Screenshot_Settings.png
  doc/Play Store/Screenshot_Shop.png
  doc/Play Store/Screenshot_Today.png
  doc/Presentation/Uniatron-Presentation0706.pptx
  doc/Presentation/Uniatron-Presentation1207.pptx
  domain/build.gradle
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/DataRepository.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/util/DateUtil.java
  domain/src/main/java/com/edu/uni/augsburg/uniatron/domain/util/LiveDataAsyncTask.java
  domain/src/test/java/android/os/AsyncTask.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/AppDatabaseTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/DataRepositoryTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/model/AppUsageEntityTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/model/EmotionEntityTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/model/StepCountEntityTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/model/SummaryEntityTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/model/TimeCreditEntityTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/util/DateUtilTest.java
  domain/src/test/java/com/edu/uni/augsburg/uniatron/domain/util/TestUtils.java
Labels: Documentation

#75 Quick fix
  README.md
  app/build.gradle
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingActivity.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingFragment.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/shop/TimeCreditShopViewModel.java
  app/src/main/res/values/strings.xml
Labels: bug

#72 Create multi-module coverage analysis
  .codecov.yml
  .travis.yml
  README.md
  app/build.gradle
  build.gradle
  domain/build.gradle
  gradle/coverage-submodule.gradle
  gradle/coverage.gradle
  gradle/test-logging.gradle
Labels: wait

#82 Place today menu item in overflow menu
  app/src/main/res/menu/nav_bottom_bar_menu.xml
Labels: enhancement

#83 Change visibility of date-buttons and fix bugs
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/MainActivity.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/MainActivityViewModel.java
  app/src/main/java/com/edu/uni/augsburg/uniatron/ui/setting/SettingActivity.java
Labels: bug, enhancement
